[AdminBundle] Load scripts in head with defer
Kunstmaan/KunstmaanBundlesCMS pull request #2378
Opened 2019-02-20 12:03 UTC by dbeerten

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | ?
| Deprecations? | no
| Fixed tickets | #1617 

**BC or not?**

We moved our scripts from the end of the body to the head with a `defer` attribute.

If you added custom javascript (for example in `_js_footer_extra.html.twig`) which depends on jQuery, your custom code might be broken because jQuery isn't available yet. If that's the case, you need to make sure to load your scripts with a `defer` attribute:
```
<script defer src="custom-jquery-script.js"></script>
```
or wait for the `DOMContentLoaded`-event for inline scripts:

```
<script>
    document.addEventListener('DOMContentLoaded', () => {
        console.log('$ and jQuery are available here.')
    });
</script>
```

FYI: https://alligator.io/html/defer-async/#async-vs-defer

2019-02-20 12:03 UTC, ProfessorKuma requested changes
Hi @dbeerten, your PR needs some changes
* Your answer if this PR is BC breaking seems to be incorrect.

2019-03-06 19:21 UTC, acrobat commented
I would move this to at least the next minor version (or even next major?) and definitely provide a warning/explanation in the upgrade doc.

2019-03-14 15:46 UTC, Numkil commented
This is indeed a bc break. The code itself is OK so if you rebase to master then we can merge this in :)

2019-03-20 15:19 UTC, ProfessorKuma requested changes
Hi @dbeerten, your PR needs some changes
* It seems that you should have submitted to the next major branch.
* This PR seems to need a milestone of a major release.

2019-03-21 16:01 UTC, Devolicious requested changes
Temporarily blocking this to be merged. We need to see if we are going to add this in V5 or V6.

2019-04-18 12:36 UTC, ProfessorKuma approved these changes
Hi @dbeerten, your PR passed all our requirements.

Thank you for contributing!

2022-04-06 13:22 UTC, closed without merging