Be able to set the target of the preview of a page
Kunstmaan/KunstmaanBundlesCMS pull request #2511
Opened 2019-07-02 12:43 UTC by devigner

| Q             | A
| ------------- | ---
| Bug fix?      |no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? |no
| Fixed tickets | none

2019-07-02 12:43 UTC, ProfessorKuma requested changes
Hi @, your PR needs some changes
* It seems that you should have submitted to master.
* This PR seems to need a milestone of a minor release.
* your PR title should look like `[SomeBundle] Fixed some code`

2019-07-02 20:10 UTC, ProfessorKuma approved these changes
Hi @, your PR passed all our requirements.

Thank you for contributing!

2019-10-18 08:41 UTC, acrobat requested changes

2022-03-23 20:59 UTC, acrobat commented
I'm closing this PR because of inactivity, if you still need this change reopen this PR and apply the requested changes.

2022-03-23 20:59 UTC, closed without merging