[AdminBundle] update fe packages
Kunstmaan/KunstmaanBundlesCMS pull request #2719
Opened 2020-08-27 12:11 UTC by FVKVN

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | yes
| Deprecations? | yes|no
| Fixed tickets | comma separated list of tickets fixed by the PR

2020-08-27 12:11 UTC, ProfessorKuma requested changes
Hi @, your PR needs some changes
* Your answer if this PR is has deprecations seems to be incorrect.
* It seems that you should have submitted to the next major branch.
* This PR seems to need a milestone of a major release.

2020-09-02 19:00 UTC, ProfessorKuma requested changes
Hi @, your PR needs some changes
* This PR seems to need a milestone of a minor release.

2020-09-04 07:04 UTC, acrobat commented
@FVKVN Can you check the failing frontend build in travis?

2020-09-04 07:05 UTC, ProfessorKuma approved these changes
Hi @, your PR passed all our requirements.

Thank you for contributing!

2020-09-17 07:10 UTC, dbeerten commented on .nvmrc
> +v10
Should't we upgrade to v12 or even 14?

2020-09-17 07:15 UTC, dbeerten commented on groundcontrol/tasks/bundle.js
> +                        'ie 11',
Maybe we should drop IE11 support by default now, as it will be EOL by 2021

2020-09-18 09:49 UTC, dbeerten commented on groundcontrol/tasks/bundle.js
> +                    useBuiltIns: 'usage',
add corejs option?

2020-09-18 09:51 UTC, dbeerten commented on groundcontrol/admin-bundle.tasks.js
> +        entry: ['babel-polyfill', `${adminBundle.config.srcPath}jsnext/polyfills.js`],
The 'mode' option has not been set: https://webpack.js.org/configuration/mode/

2020-09-20 12:36 UTC, acrobat requested changes

2020-09-20 12:36 UTC, acrobat commented on src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/package.json
> +  "name":"demo",
This change must be reverted to generate a correct name in new projects

2020-09-20 12:40 UTC, acrobat requested changes

2020-09-20 12:40 UTC, acrobat commented on package.json
> -    "postinstall": "git clone -b full/4.5.3 --single-branch https://github.com/ckeditor/ckeditor-releases.git node_modules/ckeditor"
Why is the `--single-branch` option removed? This would improve the clone as it fetches only the history for the requested branch

2020-09-20 13:07 UTC, acrobat commented
This PR breaks the frontend build on new installations

![image](https://user-images.githubusercontent.com/1374857/93711817-8b86a000-fb51-11ea-809f-f93c838c5c60.png)

2020-09-21 13:21 UTC, dbeerten commented on groundcontrol/admin-bundle.tasks.js
> +            path: path.resolve(__dirname, '../src/Kunstmaan/AdminBundle/Resources/public/js'),
Can you use the adminBundle.config here? As all other paths are in the config object

2020-09-21 13:21 UTC, dbeerten commented on groundcontrol/admin-bundle.tasks.js
> +            path: path.resolve(__dirname, '../src/Kunstmaan/AdminBundle/Resources/public/js'),
Can you use the adminBundle.config here? As all other paths are in the config object

2020-09-21 13:21 UTC, dbeerten commented on groundcontrol/admin-bundle.tasks.js
> +            path: path.resolve(__dirname, '../src/Kunstmaan/AdminBundle/Resources/public/js'),
Can you use the adminBundle.config here? As all other paths are in the config object

2020-09-21 13:22 UTC, dbeerten commented on groundcontrol/tasks/bundle.js
> +import 'core-js';
Move this to the javascript that gets bundled => jsnext/app.js

2020-09-21 13:24 UTC, dbeerten commented on groundcontrol/tasks/bundle.js
> +import 'core-js';
This can be removed

2020-09-21 19:04 UTC, acrobat requested changes

2020-09-21 19:04 UTC, acrobat commented on src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/package.json
> -    "bootstrap-sass": "^3.3.7",
This removal causes build issues in new projects

2020-09-21 19:05 UTC, acrobat commented
The build issue in the project seems to be fixed, but generating the frontend is still broken

![image](https://user-images.githubusercontent.com/1374857/93809905-29f82b80-fc4e-11ea-9a70-28361113e2be.png)

2020-09-23 12:23 UTC, acrobat approved these changes

2020-09-23 12:31 UTC, merged