Add width and height to media show
Kunstmaan/KunstmaanBundlesCMS pull request #2760
Opened 2020-09-21 07:26 UTC by dannyvw

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | #2735

2020-09-21 07:26 UTC, ProfessorKuma requested changes
Hi @, your PR needs some changes
* This PR seems to need a milestone of a minor release.
* your PR title should look like `[SomeBundle] Fixed some code`

2020-09-21 07:27 UTC, ProfessorKuma approved these changes
Hi @, your PR passed all our requirements.

Thank you for contributing!

2020-09-22 07:58 UTC, acrobat approved these changes

2020-09-22 07:58 UTC, acrobat commented
Thanks @dannyvw!

2020-09-22 07:58 UTC, merged