[MediaBundle] Update bulk move translations
Kunstmaan/KunstmaanBundlesCMS pull request #2766
Opened 2020-09-23 15:08 UTC by dannyvw

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | comma separated list of tickets fixed by the PR

2020-09-23 15:08 UTC, ProfessorKuma requested changes
Hi @, your PR needs some changes
* This PR seems to need a milestone of a minor release.

2020-09-23 15:08 UTC, ProfessorKuma approved these changes
Hi @, your PR passed all our requirements.

Thank you for contributing!

2020-09-25 12:42 UTC, acrobat approved these changes

2020-09-25 12:43 UTC, acrobat commented
Thanks @dannyvw!

2020-09-25 12:43 UTC, merged