[MediaBundle] Use parameter instead of hardcoded media path
Kunstmaan/KunstmaanBundlesCMS pull request #2782
Opened 2020-10-08 08:28 UTC by dannyvw

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yeso
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | comma separated list of tickets fixed by the PR

2020-10-08 08:28 UTC, ProfessorKuma requested changes
Hi @, your PR needs some changes
* Your answer if this PR is a new feature seems to be incorrect.

2020-10-08 08:35 UTC, ProfessorKuma requested changes
Hi @, your PR needs some changes
* This PR seems to need a milestone of a minor release.

2020-10-08 08:35 UTC, ProfessorKuma approved these changes
Hi @, your PR passed all our requirements.

Thank you for contributing!

2020-10-12 19:10 UTC, acrobat requested changes
Small change needed, but other than that it looks good!

2020-10-12 19:10 UTC, acrobat commented on src/Kunstmaan/MediaBundle/Helper/File/FileHelper.php
> +    public function __construct(Media $media, $mediaPath = null)
```suggestion
    public function __construct(Media $media, string $mediaPath = null)
```

2020-10-13 08:14 UTC, dannyvw commented on src/Kunstmaan/MediaBundle/Helper/File/FileHelper.php
> +    public function __construct(Media $media, $mediaPath = null)
@acrobat Done!

2021-03-12 11:59 UTC, dannyvw commented
@acrobat Do you have an update for this?

2021-04-25 18:49 UTC, acrobat commented
@dannyvw I'm not allowed to push extra fixes to this branch so can you check/apply these changes and rebase againt the current master? Then we should be go to go for the merge!

```diff
commit ef70ba16918f457692e60e9da8174f7de75e11bd
Author: Jeroen Thora <jeroenthora@gmail.com>
Date:   Sun Apr 25 20:48:18 2021 +0200

    Extra fixes

diff --git a/UPGRADE-5.9.md b/UPGRADE-5.9.md
new file mode 100644
index 000000000..b15611ff7
--- /dev/null
+++ b/UPGRADE-5.9.md
@@ -0,0 +1,7 @@
+UPGRADE FROM 5.8 to 5.9
+=======================
+
+MediaBundle
+------------
+
+* Not passing a value for the "$mediaPath" parameter of "\Kunstmaan\MediaBundle\Helper\File\FileHelper::__construct" is deprecated, a value will be required.
diff --git a/src/Kunstmaan/MediaBundle/Helper/File/FileHelper.php b/src/Kunstmaan/MediaBundle/Helper/File/FileHelper.php
index d0e0778e0..2b2d4dbf6 100644
--- a/src/Kunstmaan/MediaBundle/Helper/File/FileHelper.php
+++ b/src/Kunstmaan/MediaBundle/Helper/File/FileHelper.php
@@ -28,18 +28,20 @@ class FileHelper
      */
     protected $path;
 
-    protected $mediaPath;
+    /** @var string */
+    private $mediaPath;
 
     /**
-     * @param Media  $media
-     * @param string $mediaPath
+     * @param Media       $media
+     * @param string|null $mediaPath
      */
     public function __construct(Media $media, string $mediaPath = null)
     {
         $this->media = $media;
 
         if ($mediaPath === null) {
-            @trigger_error(sprintf('Not passing the media path as the second argument of "%s" is deprecated since KunstmaanMediaBundle 5.7 and will be required in KunstmaanMediaBundle 6.0. Injected the required parameter in the constructor instead.', __METHOD__), E_USER_DEPRECATED);
+            @trigger_error(sprintf('Not passing a value for the "$mediaPath" parameter of "%s" is deprecated since KunstmaanMediaBundle 5.9 and a value will be required in KunstmaanMediaBundle 6.0. Injected the required parameter in the constructor instead.', __METHOD__), E_USER_DEPRECATED);
+
             $mediaPath = '/uploads/media/';
         }
```

2021-05-08 12:48 UTC, acrobat approved these changes

2021-05-08 12:49 UTC, merged

2021-05-08 12:49 UTC, acrobat commented
Thanks @dannyvw!