[GeneratorBundle] Remove buildCmsAssets from generated FE tasks - ass…
Kunstmaan/KunstmaanBundlesCMS pull request #2797
Opened 2020-10-19 09:55 UTC by dbeerten

…ets are compiled in git repo

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | yes
| Fixed tickets | #2440

2020-10-19 09:55 UTC, ProfessorKuma requested changes
Hi @, your PR needs some changes
* It seems that our checklist is missing or incomplete

2020-10-19 09:55 UTC, ProfessorKuma requested changes
Hi @, your PR needs some changes
* This PR seems to need a milestone of a minor release.

2020-10-19 12:53 UTC, ProfessorKuma approved these changes
Hi @, your PR passed all our requirements.

Thank you for contributing!

2020-10-21 18:49 UTC, acrobat approved these changes

2020-10-21 18:49 UTC, merged