[AdminBundle] autofocus search input when opening modal
Kunstmaan/KunstmaanBundlesCMS pull request #2798
Opened 2020-10-19 14:45 UTC by dbeerten

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets |

Autofocus the search input when opening the visual pagepart chooser
![image](https://user-images.githubusercontent.com/5577291/96466749-73766f00-122a-11eb-83ac-d1bc6efbeeb7.png)

2020-10-19 14:45 UTC, ProfessorKuma approved these changes
Hi @, your PR passed all our requirements.

Thank you for contributing!

2020-10-19 19:25 UTC, acrobat approved these changes

2020-10-19 19:26 UTC, ProfessorKuma requested changes
Hi @, your PR needs some changes
* This PR seems to need a milestone of a minor release.

2020-10-20 07:28 UTC, ProfessorKuma approved these changes
Hi @, your PR passed all our requirements.

Thank you for contributing!

2020-10-20 11:03 UTC, acrobat approved these changes

2020-10-20 11:03 UTC, merged