[NodeSearchBundle] Allow include offline option get_parent twig function.
Kunstmaan/KunstmaanBundlesCMS pull request #2800
Opened 2020-10-22 07:52 UTC by Numkil

| Q             | A
| ------------- | ---
| Bug fix?      | yno
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | 

Because in a private project we had run into this as a problem in the admin view and had to make our own twig function. It would be easier if this was an option straight out of the box.

2020-10-22 07:52 UTC, ProfessorKuma requested changes
Hi @, your PR needs some changes
* Your answer if this PR is a bugfix seems to be incorrect.
* This PR seems to need a milestone of a minor release.

2020-10-22 07:52 UTC, ProfessorKuma approved these changes
Hi @, your PR passed all our requirements.

Thank you for contributing!

2020-10-30 11:59 UTC, acrobat approved these changes

2020-10-30 12:00 UTC, acrobat requested changes

2020-10-30 12:00 UTC, acrobat commented on src/Kunstmaan/NodeSearchBundle/Twig/KunstmaanNodeSearchTwigExtension.php
> -     * @return HasNodeInterface
Can you keep the return type phpdoc?

2020-10-30 12:46 UTC, acrobat approved these changes

2020-11-02 10:07 UTC, merged