[All Bundles] Added PostgreSQL support
Kunstmaan/KunstmaanBundlesCMS pull request #2811
Opened 2020-11-03 23:05 UTC by igst

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | -

Based on https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/1778 and https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/1810

This PR makes it possible to use Kunstmaan Bundles CMS with a PostgreSQL database.

2020-11-03 23:05 UTC, ProfessorKuma requested changes
Hi @, your PR needs some changes
* It seems that you should have submitted to the latest minor branch.
* This PR seems to need a milestone of a patch release.

2020-11-04 13:01 UTC, igst commented on src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Repository/PageRepositoryPartial.php.twig
>              ->setParameter('refname', "{{ namespace | replace({'\\': '\\\\'}) }}\\Entity\\Pages\\{{ entity_class }}Page");
//// is only required in LIKE clause and should not work with "="

2020-11-20 14:36 UTC, acrobat reviewed
Few questions. I will also test this PR on some actually projects to avoid any breaks there

2020-11-20 14:36 UTC, acrobat commented on src/Kunstmaan/AdminBundle/Helper/Security/Acl/AclHelper.php
>  WHERE c.class_type = {$rootEntity}
Do we need quotes here? https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/1778/files#diff-2ae42119f573a6a61e26009641aa186d97e0f77b951dc02385d67d9daa075854R193

2020-11-20 14:36 UTC, acrobat commented on src/Kunstmaan/AdminBundle/Helper/Security/Acl/AclNativeHelper.php
>  WHERE c.class_type = {$rootEntity}
Same question as comment above

2021-03-15 21:17 UTC, acrobat commented
I'm closing the PR in favor of #2849, the implentation will be finished there. Thanks for your work on this @igst!

2021-03-15 21:17 UTC, closed without merging