Fix: Wrong namespace
Kunstmaan/KunstmaanBundlesCMS pull request #2813
Opened 2020-11-04 12:48 UTC by OskarStark

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | comma separated list of tickets fixed by the PR

2020-11-04 12:50 UTC, ProfessorKuma requested changes
Hi @, your PR needs some changes
* It seems that you should have submitted to the latest minor branch.
* This PR seems to need a milestone of a patch release.
* your PR title should look like `[SomeBundle] Fixed some code`

2020-11-04 12:55 UTC, OskarStark commented
> It seems that you should have submitted to the latest minor branch.

@acrobat AFAIK, the latest released version is `5.7.1`, so base `5.7` should be correct, right? 🤔

2020-11-04 19:14 UTC, acrobat commented
@OskarStark Yes indeed 5.7.1 is the latest release but the 5.6.x is still supported and will receive bugfixes. Some time in the future we will move active support to 5.7 but there will be a milestone for the least supported version so that should be an indicator which branch is still supported!

So if you can rebase this PR on the 5.6? Thanks!

2020-11-04 20:12 UTC, OskarStark commented
HI @acrobat 👋 

First of all, thanks for the explanation, maybe it should be made more clear what you mean by
> It seems that you should have submitted to the latest minor branch

Can you please also answer my question regarding the `unit/` folder from the PR header? Thanks. It violates PSR-4 AFAIK 

> @acrobat can you explain the unit/ in the path, but not in the namespace? Also unit/ is not handled properly in composer.json 🤔

2020-11-05 06:57 UTC, acrobat commented
@OskarStark You are right, we will look into improving the bot message to already suggest the correct branch!

About the `unit` folder, this is a left over of a previous codeception implementation, so the unit folder should indeed be removed the make the current namespace work and be correct. If you can remove the excess folder in this pr, that would be awesome!

2020-11-05 07:42 UTC, OskarStark commented
I will provide a new PR against 5.6 and fix the folder plus namespaces ￼

2020-11-05 14:20 UTC, OskarStark commented
Superseded by #2818

2020-11-05 14:20 UTC, closed without merging