[AdminListBundle] Enhancement: Streamline tests
Kunstmaan/KunstmaanBundlesCMS pull request #2818
Opened 2020-11-05 14:16 UTC by OskarStark

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  |no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | --

This PR

* [x] is based on https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/2813#issuecomment-722183497
* [x] removes useless comments
* [x] fix namespaces
* [x] removes `unit` folder to not violate PSR-4
* [x] replaces #2813

2020-11-05 14:16 UTC, ProfessorKuma requested changes
Hi @, your PR needs some changes
* This PR seems to need a milestone of a patch release.

2020-11-05 14:16 UTC, ProfessorKuma approved these changes
Hi @, your PR passed all our requirements.

Thank you for contributing!

2020-11-05 17:23 UTC, acrobat requested changes
Can you check the failing styleci check? Travis also fails but will be fixed I think with the suggested code change

2020-11-05 17:23 UTC, acrobat commented on src/Kunstmaan/AdminListBundle/Tests/Service/EntityVersionLockServiceTest.php
> +    protected static $TEST_CLASS = 'Kunstmaan\\AdminListBundle\\Tests\\\Model\\TestLockableEntityInterfaceImplementation';
```suggestion
    protected static $TEST_CLASS = 'Kunstmaan\\AdminListBundle\\Tests\\Model\\TestLockableEntityInterfaceImplementation';
```

One `\` too many

2020-11-05 17:59 UTC, OskarStark commented
Sure will check tomorrow

2020-11-05 20:06 UTC, OskarStark commented on src/Kunstmaan/AdminListBundle/Tests/AdminList/FilterType/DBAL/DateTimeFilterTypeTest.php
> +
```suggestion
```

2020-11-05 20:12 UTC, OskarStark commented on src/Kunstmaan/AdminListBundle/Tests/AdminList/FilterType/DBAL/EnumerationFilterTypeTest.php
> +
```suggestion
```

2020-11-05 20:13 UTC, OskarStark commented on src/Kunstmaan/AdminListBundle/Tests/AdminList/FilterType/DBAL/StringFilterTypeTest.php
> +
```suggestion
```

2020-11-05 20:13 UTC, OskarStark commented on src/Kunstmaan/AdminListBundle/Tests/AdminList/FilterType/DBAL/NumberFilterTypeTest.php
> +
```suggestion
```

2020-11-06 07:21 UTC, acrobat approved these changes

2020-11-06 07:21 UTC, acrobat commented
Thanks @OskarStark!

2020-11-06 07:21 UTC, merged