[FormBundle] Add length validation to string form field
Kunstmaan/KunstmaanBundlesCMS pull request #2843
Opened 2021-01-07 12:58 UTC by dannyvw

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | comma separated list of tickets fixed by the PR

The max length in the database is 255. Without validation you get an database error.

2021-01-07 12:58 UTC, ProfessorKuma requested changes
Hi @, your PR needs some changes
* It seems that you should have submitted to the latest minor branch.
* This PR seems to need a milestone of a patch release.

2021-01-13 18:51 UTC, acrobat requested changes
Minor comment, otherwise good to merge!

2021-01-13 18:51 UTC, acrobat commented on src/Kunstmaan/FormBundle/Entity/FormSubmissionFieldTypes/StringFormSubmissionField.php
> +     *     max=255
minor comment but can you keep it all on one line? Thanks!

2021-01-19 17:10 UTC, acrobat approved these changes

2021-01-19 17:11 UTC, ProfessorKuma approved these changes
Hi @, your PR passed all our requirements.

Thank you for contributing!

2021-01-19 17:11 UTC, ProfessorKuma submitted a review, later dismissed
Hi @, your PR needs some changes
* It seems that you should have submitted to the latest minor branch.

2021-01-19 17:12 UTC, acrobat commented
Thanks @dannyvw!

2021-01-19 17:13 UTC, merged