[NodeBundle] fixed unpublish later
Kunstmaan/KunstmaanBundlesCMS pull request #2845
Opened 2021-01-14 12:46 UTC by puzon

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | 2844

2021-01-14 12:47 UTC, ProfessorKuma requested changes
Hi @, your PR needs some changes
* It seems that you should have submitted to the latest minor branch.
* This PR seems to need a milestone of a patch release.

2021-03-15 21:13 UTC, acrobat approved these changes

2021-03-15 21:15 UTC, ProfessorKuma approved these changes
Hi @, your PR passed all our requirements.

Thank you for contributing!

2021-03-15 21:16 UTC, merged

2021-03-15 21:16 UTC, acrobat commented
Thanks @puzon! And congrats on your first contribution! 🎉