[MultidomainBundle] Fix getting host when its not available
Kunstmaan/KunstmaanBundlesCMS pull request #2870
Opened 2021-04-20 11:41 UTC by JZuidema

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets |

In one of our already existing live projects, we decided to add the kunstmaan/multidomain-bundle. It works fine, but it seems to break internal links.
If you do not use the kunstmaan/multidomain-bundle, internal links look like [NT45].
When using the `|replace_url` filter in twig, it uses this the method replaceUrl (at kunstmaan/bundles-cms/src/Kunstmaan/NodeBundle/Helper/URLHelper.php:59). Here it expects the domain to be in the internal link when using the kunstmaan/multidomain-bundle:

```php
                    $hostConfig = !empty($hostId) ? $this->domainConfiguration->getFullHostById($hostId) : null;
                    $host = null !== $hostConfig && array_key_exists('host', $hostConfig) ? $hostConfig['host'] : null;
                    $hostBaseUrl = $this->domainConfiguration->getHostBaseUrl($host);
```

And this is where it breaks. `$host` is null, because it cannot be extracted from `[NT45]`, but in the method `getHostBaseUrl()` it tries to access `$config['protocol']` and `$config['host']` when `$config` is actually `null`

2021-04-20 11:41 UTC, ProfessorKuma requested changes
Hi @, your PR needs some changes
* This PR seems to need a milestone of a patch release.

2021-04-20 11:41 UTC, ProfessorKuma approved these changes
Hi @, your PR passed all our requirements.

Thank you for contributing!

2021-04-24 14:59 UTC, acrobat requested changes
Hi @JZuidema, the fix looks good but can you also add a test for this case so we avoid regressions in the future!

2022-02-02 13:44 UTC, Marijnk7 commented
Hi @acrobat, i've added a test for the fix.

2022-02-03 10:13 UTC, acrobat commented
@Marijnk7 Thanks for the added test! Can you check the test results as the new test case seems to fail. Also can you rebase this PR (and switch the PR base to) on the current 5.10 branch as this is only branch that receives bugfixes. Thanks!

2022-02-06 16:30 UTC, acrobat commented
@JZuidema @Marijnk7 Thanks for the initial fixes! I've ran into the same issue in a project of ours so I've fixed the failing test and did the rebase. Closing this in favor of #3071.

2022-02-06 16:30 UTC, closed without merging