WIP new login styling
Kunstmaan/KunstmaanBundlesCMS pull request #2888
Opened 2021-06-10 14:31 UTC by dbeerten

| Q             | A
| ------------- | ---
| Bug fix?      | yes|no
| New feature?  | yes|no
| BC breaks?    | yes|no
| Deprecations? | yes|no
| Fixed tickets | comma separated list of tickets fixed by the PR

2021-06-10 14:31 UTC, ProfessorKuma requested changes
Hi @, your PR needs some changes
* Your answer if this PR is a bugfix seems to be incorrect.
* Your answer if this PR is a new feature seems to be incorrect.
* Your answer if this PR is BC breaking seems to be incorrect.
* Your answer if this PR is has deprecations seems to be incorrect.
* your PR title should look like `[SomeBundle] Fixed some code`

2021-06-13 19:58 UTC, acrobat requested changes

2021-06-13 19:58 UTC, acrobat commented on src/Kunstmaan/AdminBundle/Resources/views/Default/layout.html.twig
> +{#    {% include "@KunstmaanAdmin/Default/_css_extra.html.twig" %}#}
Do we need to uncomment or remove this line? (and uncomment line 35?)

2021-06-13 19:58 UTC, acrobat commented on src/Kunstmaan/AdminBundle/Resources/views/authentication/email/password_reset.html.twig
> +{# TODO: html template, teksten in translations #}
Remove todo comment

2021-06-13 19:58 UTC, acrobat commented on src/Kunstmaan/AdminBundle/Resources/views/authentication/login.html.twig
> +        Log in to {{ websitetitle | trans }}
We need to move this to a translation key

2021-06-13 19:58 UTC, acrobat commented on src/Kunstmaan/AdminBundle/Resources/views/authentication/login.html.twig
>      {% if google_signin_enabled() %}
Can you check if the signin with google button also show correct in the new layout? (Can be temporary "faked" by commenting the if statement)

2021-06-13 19:58 UTC, acrobat commented on src/Kunstmaan/AdminBundle/Resources/views/authentication/layout.html.twig
> +                        <img src="/bundles/kunstmaanadmin/default-theme/img/kunstmaan/logo-cms-color.svg" class="app-login__footer__logo">
Can you add the `asset` function around the image path?

2021-06-13 19:58 UTC, acrobat commented on src/Kunstmaan/AdminBundle/Resources/views/authentication/layout.html.twig
> +                {% set login_image_url = '/bundles/kunstmaanadmin/default-theme/img/kunstmaan/default-login-bg.jpg' %}
Can you add the `asset` function around the image path?

2021-06-13 19:58 UTC, acrobat commented on src/Kunstmaan/AdminBundle/Resources/views/authentication/layout.html.twig
> +                            {{ 'layout.logged_in_as'|trans({'%username%': app.user.username}, 'FOSUserBundle') }}
```suggestion
                            {{ 'layout.logged_in_as'|trans({'%username%': app.user.username}) }}
```

2021-06-13 19:58 UTC, acrobat commented on src/Kunstmaan/AdminBundle/Resources/views/authentication/layout.html.twig
> +                                {{ 'layout.logout'|trans({}, 'FOSUserBundle') }}
```suggestion
                                {{ 'layout.logout'|trans }}
```

2021-06-13 20:50 UTC, ProfessorKuma requested changes
Hi @, your PR needs some changes
* This PR seems to need a milestone of a minor release.

2021-06-13 20:50 UTC, ProfessorKuma approved these changes
Hi @, your PR passed all our requirements.

Thank you for contributing!

2021-07-25 14:27 UTC, acrobat approved these changes

2021-07-25 14:28 UTC, merged