[AllBundles] Update sortablejs back to 1.8.1
Kunstmaan/KunstmaanBundlesCMS pull request #2892
Opened 2021-06-14 09:50 UTC by dannyvw

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | #2873

2021-06-14 09:50 UTC, ProfessorKuma requested changes
Hi @, your PR needs some changes
* This PR seems to need a milestone of a patch release.

2021-06-14 09:50 UTC, ProfessorKuma approved these changes
Hi @, your PR passed all our requirements.

Thank you for contributing!

2021-07-04 13:56 UTC, acrobat requested changes
1 minor comment, otherwise this PR is ready to merged. I've this on a new install and sorting is again working correctly.

Also revert the package-lock.json changes, this makes merging/upmerging easier and it will be updated on release when all assets are generated

2021-07-04 13:56 UTC, acrobat commented on package.json
> +    "sortablejs": "1.8.1",
```suggestion
    "sortablejs": "^1.8.1",
```

2021-07-05 11:48 UTC, dannyvw commented
@acrobat Done!

2021-07-05 16:02 UTC, acrobat approved these changes

2021-07-05 16:02 UTC, merged

2021-07-05 16:02 UTC, acrobat commented
Thanks @dannyvw!