[MediaBundle] Fix for removing media files and directories
Kunstmaan/KunstmaanBundlesCMS pull request #2932
Opened 2021-08-03 15:08 UTC by Minhan12

This pull request will fix 2 bugs in the MediaBundle.

1. When using the command `php bin/console kuma:media:clean-deleted-media --force` to delete the files by the original filename, it will skip the files from the filesystem that have been renamed due to strange characters in the filename. Using the command `php bin/console kuma:media:rename-soft-deleted -o` will update the filename back to the original filename. However, it doesn't use the same method as when an user uploads a file so this command will not update the filename correctly.
This fix will add the slugifier to the command so it will pass the same method when renaming the filename.

2. The command also expects the directory to be deleted. however, it uses a directory name to check if a file exists, so it fail on the check so it doesn't delete the directory.

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | none

2021-08-03 15:08 UTC, ProfessorKuma requested changes
Hi @, your PR needs some changes
* It seems that our checklist is missing or incomplete

2021-08-03 15:10 UTC, ProfessorKuma requested changes
Hi @, your PR needs some changes
* It seems that you should have submitted to the latest minor branch.
* This PR seems to need a milestone of a patch release.

2021-08-13 18:03 UTC, acrobat requested changes
Thanks for the pr @Minhan12! Can you also rebase this PR against the 5.6 branch? Thanks!

I've also left a few comments

2021-09-20 12:48 UTC, Minhan12 commented on src/Kunstmaan/MediaBundle/Helper/File/FileHandler.php
> +        if ($adapter->isDirectory($folderPath) && !empty($folderPath)) {
The isDirectory will check if the directory exists with the method `ensureDirectoryExists` from the FlySystem.

So the call to the method exists() seems double

2022-01-05 14:51 UTC, closed without merging