[AdminBundle] Add hide sidebar configuration
Kunstmaan/KunstmaanBundlesCMS pull request #3333
Opened 2024-02-21 09:20 UTC by dannyvw

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | comma separated list of tickets fixed by the PR

Add global option to hide sidebar

2024-03-05 18:37 UTC, acrobat requested changes
Can you also rebase against the latest 6.x branch, this should fix the failing tests? Thanks!

2024-03-05 18:37 UTC, acrobat commented on src/Kunstmaan/AdminBundle/DependencyInjection/Configuration.php
> +            ->booleanNode('hide_sidebar')->defaultFalse()->end();
Doesn't this need to be flipped? First the new option and than the closing end method?
```suggestion
                ->booleanNode('hide_sidebar')->defaultFalse()->end()
            ->end();
```

2024-03-06 08:45 UTC, dannyvw commented on src/Kunstmaan/AdminBundle/DependencyInjection/Configuration.php
> +            ->booleanNode('hide_sidebar')->defaultFalse()->end();
The end is from password_restrictions

2024-03-10 15:54 UTC, acrobat approved these changes

2024-03-10 15:54 UTC, merged

2024-03-10 15:54 UTC, acrobat commented
Thanks @dannyvw