Refactor Url chooser without XHR call
Kunstmaan/KunstmaanBundlesCMS pull request #3432
Opened 2024-08-29 09:00 UTC by mart-insiders

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | comma separated list of tickets fixed by the PR

2025-01-26 19:08 UTC, acrobat requested changes
Feature works good 👌 I've add a few comments and question but overall it looks alright!

2025-01-26 19:08 UTC, acrobat commented on src/Kunstmaan/NodeBundle/DependencyInjection/KunstmaanNodeExtension.php
> +
Can you add check to deprecate not settings this option?

```
        if (!$enableImprovedUrlchooser) {
            trigger_deprecation('kunstmaan/node-bundle', '7.2', 'Not setting the "kunstmaan_node.enable_improved_urlchooser" config to true is deprecated, it will always be true in 8.0.');
        }
```

2025-01-26 19:08 UTC, acrobat commented on src/Kunstmaan/NodeBundle/Form/EventListener/URLChooserFormSubscriber.php
> +/** @deprecated  */
```suggestion
/** 
 * @deprecated since 7.2 and will be removed in 8.0. Switch to the improved url chooser instead.
 */
```

2025-01-26 19:08 UTC, acrobat commented on src/Kunstmaan/NodeBundle/Form/EventListener/URLChooserLinkTypeSubscriber.php
> +/** @deprecated */
```suggestion
/** 
 * @deprecated since 7.2 and will be removed in 8.0. Switch to the improved url chooser instead.
 */
```

2025-01-26 19:08 UTC, acrobat commented on src/Kunstmaan/NodeBundle/Resources/config/services.yml
> +            $improvedUrlChooser: '%kunstmaan_node.enable_improved_urlchooser%'
Please don't use named parameters here as function parameter names are not covered by the BC policy

2025-01-26 19:08 UTC, acrobat commented on src/Kunstmaan/AdminBundle/Resources/ui/js/_url-chooser.js
> +            // deprecated, use adaptUrl(e.target) when enable_improved_urlchooser becomes standard
Can you explain what is exactly deprecated? So I understand what to remove in 8.0

2025-01-27 07:23 UTC, mart-insiders commented on src/Kunstmaan/AdminBundle/Resources/ui/js/_url-chooser.js
> +            // deprecated, use adaptUrl(e.target) when enable_improved_urlchooser becomes standard
The onclick event should trigger the function adaptUrl for the improved url chooser.
Everything below that is deprecated and only used for the current url chooser.
So, everything from r.222 `var $form = $(this).closest('form'),` untill r.264 `});` is deprecated

2025-01-27 07:43 UTC, mart-insiders commented on src/Kunstmaan/NodeBundle/DependencyInjection/KunstmaanNodeExtension.php
> +
added!

2025-01-27 07:43 UTC, mart-insiders commented on src/Kunstmaan/NodeBundle/Resources/config/services.yml
> +            $improvedUrlChooser: '%kunstmaan_node.enable_improved_urlchooser%'
changed to unnamed parameter

2025-01-31 21:10 UTC, acrobat commented
Thanks @mart-insiders!

2025-01-31 21:10 UTC, merged