[NodeBundle] Improve url helper performance
Kunstmaan/KunstmaanBundlesCMS pull request #3474
Opened 2024-11-21 11:49 UTC by dannyvw

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | comma separated list of tickets fixed by the PR

Improve performance by reducing getHost calls

2025-02-15 16:17 UTC, acrobat requested changes
Can you also add a test to confirm the multidomain setup working. If quickly created some some this, you can use this as a basis (maybe this is already enough)

```diff
diff --git a/src/Kunstmaan/NodeBundle/Tests/Helper/UrlHelperTest.php b/src/Kunstmaan/NodeBundle/Tests/Helper/UrlHelperTest.php
index 1f05e02c4..25949c7a5 100644
--- a/src/Kunstmaan/NodeBundle/Tests/Helper/UrlHelperTest.php
+++ b/src/Kunstmaan/NodeBundle/Tests/Helper/UrlHelperTest.php
@@ -70,6 +70,26 @@ class UrlHelperTest extends TestCase
         $this->assertEquals('/abc-3', $urlHelper->replaceUrl('[NT3]'));
     }
 
+    public function testReplaceUrlWithInternalMultiDomainLink()
+    {
+        $em = $this->getMockBuilder(EntityManager::class)->disableOriginalConstructor()->getMock();
+        $em->expects($this->once())->method('getConnection')->willReturn($this->connection);
+        $router = $this->getMockBuilder(RouterInterface::class)->getMock();
+        $router->method('generate')->with('_slug', ['url' => 'abc-3', 'otherSite' => 'test_host'])->willReturn('/abc-3');
+        $domainConfig = $this->getMockBuilder(DomainConfigurationInterface::class)->getMock();
+        $domainConfig->expects($this->exactly(2))->method('getFullHostById')->with('test_host')->willReturn(['id' => 'test_host', 'host' => 'testhost.tld']);
+        $domainConfig->expects($this->exactly(2))->method('getHostBaseUrl')->with('testhost.tld')->willReturn('https://testhost.tld');
+
+        $urlHelper = new URLHelper($em, $router, new NullLogger(), $domainConfig);
+        $this->assertEquals('https://testhost.tld/abc-3', $urlHelper->replaceUrl('[test_host:NT3]'));
+
+        // Remove all records to test cached result on second call
+        $this->connection->executeStatement('DELETE FROM kuma_node_translations');
+
+        // Second call to replaceUrl should not execute query again
+        $this->assertEquals('https://testhost.tld/abc-3', $urlHelper->replaceUrl('[test_host:NT3]'));
+    }
+
     public function testReplaceUrlWithMediaLink()
     {
         $em = $this->getMockBuilder(EntityManager::class)->disableOriginalConstructor()->getMock();
```

2025-02-15 16:17 UTC, acrobat commented on src/Kunstmaan/NodeBundle/Helper/URLHelper.php
> +                $nodeTranslationId = $isSchemaLink ? $match[6] : $match[3];
I'm not sure if `$match[6]` is correct as there are only 4 capture groups in the regex (so array key 0 to 3)

2025-02-15 16:17 UTC, acrobat commented on src/Kunstmaan/NodeBundle/Helper/URLHelper.php
> +                $hostId = $isSchemaLink ? $match[5] : $match[2];
Same here `$match[5]` does not exist I think

2025-02-17 07:58 UTC, dannyvw commented on src/Kunstmaan/NodeBundle/Helper/URLHelper.php
> +                $nodeTranslationId = $isSchemaLink ? $match[6] : $match[3];
You're right. I created the PR based on our fork and issue https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/1938. I will update the PR.

2025-02-17 13:14 UTC, acrobat approved these changes

2025-02-17 13:14 UTC, acrobat commented
Thanks @dannyvw!

2025-02-17 13:14 UTC, merged